# Generated by Django 3.2.16 on 2023-03-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=155)),
                ('subject', models.CharField(max_length=495)),
                ('message', models.TextField(max_length=2499)),
            ],
        ),
    ]
